version: '3.1'
services:

  nginx: # nginx uses as reverse proxy destination in local test
    container_name: nginx
    image: nginx
    environment:
    - NGINX_PORT=8080
    ports:
    - 8080:8080

  caddy:
    container_name: caddy
    domainname: caddypoc
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./cdata:/data
      - ./cfile:/etc/caddy
    depends_on:
      - nginx